apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: spak-platform-development

namespace: spak-platform-dev

namePrefix: dev-

resources:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: spak-backend-config
    namespace: spak-platform-dev
  data:
    NODE_ENV: "development"
    MONGODB_URI: "mongodb://dev-spak-mongodb:27017/spak_communication_dev"
    REDIS_URL: "redis://dev-spak-redis:6379"
    GITHUB_CALLBACK_URL: "https://dev-api.spak.com/api/v1/auth/github/callback"
    FRONTEND_URL: "https://dev.spak.com"
    LOG_LEVEL: "debug"

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: spak-frontend-config
    namespace: spak-platform-dev
  data:
    REACT_APP_API_URL: "https://dev-api.spak.com"
    REACT_APP_ENVIRONMENT: "development"

replicas:
- name: spak-backend
  count: 1
- name: spak-frontend
  count: 1
- name: spak-nginx
  count: 1

images:
- name: spak-backend
  newTag: dev-latest
- name: spak-frontend
  newTag: dev-latest

commonLabels:
  environment: development