# Development override for Docker Compose
version: '3.8'

services:
  # Override app service for development
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules  # Anonymous volume to preserve node_modules
      - app-logs:/app/logs
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    command: npm run dev
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    read_only: false  # Allow writes in development
    security_opt: []  # Remove security restrictions for development

  # Development MongoDB (less restrictive)
  mongo:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-dev-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Development Redis (less restrictive)
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data

  # Optional development tools
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mongo-dev-data:
    driver: local
  redis-dev-data:
    driver: local