apiVersion: v1
kind: Secret
metadata:
  name: spak-backend-secrets
  namespace: spak-platform
  labels:
    app.kubernetes.io/name: spak-backend
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  JWT_REFRESH_SECRET: eW91ci1qd3QtcmVmcmVzaC1zZWNyZXQta2V5  # your-jwt-refresh-secret-key
  GITHUB_CLIENT_ID: eW91ci1naXRodWItY2xpZW50LWlk  # your-github-client-id
  GITHUB_CLIENT_SECRET: eW91ci1naXRodWItY2xpZW50LXNlY3JldA==  # your-github-client-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: spak-mongodb-secrets
  namespace: spak-platform
  labels:
    app.kubernetes.io/name: spak-mongodb
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded secrets
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123

---
apiVersion: v1
kind: Secret
metadata:
  name: spak-tls-secret
  namespace: spak-platform
  labels:
    app.kubernetes.io/name: spak-nginx
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Your TLS certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Your TLS private key