global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'spak-platform'
    environment: 'development'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spak Backend
  - job_name: 'spak-backend'
    static_configs:
      - targets: ['spak-backend:3001']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s

  # MongoDB (requires mongodb_exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-proxy:9323']
    scrape_interval: 30s

# Alerting rules
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093